config/routes.rb
Rails.application.routes.draw do
  resources :notes, except: [:edit, :update, :destroy]

  root 'notes#index'

end

app/models/note.rb
class Note
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :body, type: String
  embeds_many :tags, :inverse_of => :note

  # Model Validations
  validates_presence_of :title, :body

  # This will help to white list tag's attributes while creating note
  accepts_nested_attributes_for :tags,
                                :allow_destroy => true,
                                :reject_if => :all_blank

end

app/models/tag.rb
class Tag
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  embedded_in :note, :inverse_of => :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show]

  # GET /notes
  # GET /notes.json
  def index
    @export_notes = Note.all.order('created_at ASC')
    @notes = @export_notes.page(params[:page]).per(20)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
    10.times { @note.tags.build } # Maximum number of tags is set to 10
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def note_params
    params.require(:note).permit(:title, :body, :tags_attributes => [:title])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NotesAndTags</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <h2 class="col-sm-3"><%= link_to "Home", root_path , id: "logo" %></h2>
    <h2 class="col-sm-6"> Notes and Tags</h2>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note, :html => { :class => 'form-horizontal' } do |f| %>
    <% if @note.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

          <ul>
            <% @note.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <br>

    <div class="form-group">
      <%= f.label :title, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-4">
        <%= f.text_field :title, :class => 'form-control', :required => true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :body, :class => 'col-sm-2 control-label' %><br>
      <div class="col-sm-4">
        <%= f.text_area :body, :class => 'form-control', :rows => 5, :required => true %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :tags, :class => 'col-sm-2 control-label'%>
      <div class="col-sm-3">
        <% index = 1 %>
        <%= f.fields_for :tags do |t| %>
            <div class="single-tag" id="tag-<%= index %>" style="display: <%= index == 1 ? '' : 'none' %>">
              <%= t.text_field :title, :class => 'form-control'%>
            </div>
            <% index += 1 %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2" >
        <div class="col-sm-2 btn btn-default" id="more-tags"> Add More Tags </div>
      </div>
    </div>

    <div class="form-actions">
      <div class="col-sm-offset-2">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to 'Cancel', root_path, :class => 'btn btn-default' %>
      </div>
    </div>
<% end %>

<script>
  $(document).ready(function(){
    var tagIndex = 1;
    var maxNoTags = 10;

    $('#more-tags').click(function(){
      tagIndex = tagIndex + 1;
      if(tagIndex > maxNoTags) {
        alert("Could not add more than " + maxNoTags + " timings");
      } else {
        $('#tag-' + tagIndex).toggle();
      }
    })
  })
</script>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<ol class="breadcrumb">
  <li> Notes (<%= @notes.total_count%>)</li>
</ol>

<div class="container">
  <div>
    <%= link_to "New Note", new_note_path, class: "btn btn-lg btn-primary create-note" %>
  </div>

  <div class="new_with_pagination">
    <%= paginate @notes %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th class="col-sm-1">SN</th>
        <th class="col-sm-2">Title</th>
        <th class="col-sm-4">Body</th>
        <th class="col-sm-2">Tags</th>
        <th class="col-sm-2">Created At</th>
        <th class="col-sm-1">Action</th>
      </tr>
    </thead>

    <tbody>
    <% @notes.each_with_index do |note, index| %>
        <tr>
          <td><%= index + ((params[:page] || 1).to_i - 1) * 20 + 1 %></td>
          <td><%= note.title %></td>
          <td><%= note.body %></td>
          <td><%= note.tags.pluck(:title) %></td>
          <td><%= note.created_at %></td>
          <td><%= link_to 'Show', note %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <div class="new_with_pagination">
    <%= paginate @notes %>
  </div>
</div>

app/views/notes/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Notes", notes_path  %></li>
  <li> New </li>
</ol>

<div class="container">
  <%= render 'form' %>
</div>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb">
  <li><%= link_to "Notes", notes_path  %></li>
  <li><%= @note.title %></li>
</ol>

<div class="container">
  <dl class="dl-horizontal">
    <dt><strong>Id:</strong></dt>
    <dd><%= @note.id %></dd>
    <dt><strong>Title:</strong></dt>
    <dd><%= @note.title %></dd>
    <dt><strong>Body:</strong></dt>
    <dd><%= @note.body %></dd>
    <dt><strong>Tags:</strong></dt>
    <dd>
      <% @note.tags.each do|tag| %>
          <div><%= tag.title %></div>
      <% end %>
    </dd>
  </dl>

  <div class="form-actions">
    <div class="col-sm-offset-1">
      <%= link_to 'Back', root_path, :class => 'btn btn-default' %>
    </div>
  </div>
</div>